[build]
  # The `command` field is left empty for a static site with no build process.
  # The `&&` operator then executes the `curl` command to trigger the GitHub release.
  # This command sends a POST request to the GitHub API.
  command = "curl -X POST -H 'Authorization: token $RELEASE_TOKEN' -H 'Accept: application/vnd.github.v3+json'