[build]
  # The command is empty because a static site does not require a build step.
  # The '&&' ensures the 'curl' command only runs if the build is successful.
  # It then calls the GitHub API to create a new release.
  command = "curl -X POST -H 'Authorization: token $RELEASE_TOKEN' -H 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/sban2009/Bulk-Image-Watermark/releases -d '{\"tag_name\":\"$COMMIT_REF\", \"name\":\"$COMMIT_REF\", \"body\":\"New release from Netlify build\"}'"

  # The publish directory is where Netlify should find the files to deploy.
  publish = "/"